config {
  type: "table",
  name: "kpi_01",
  schema: "transformation",
  tags: "table_Kpi_01",
  description: "Transformierte Rohdaten. Bereinigung der Namen etc.."
}

-- SELECT * FROM ${ref("JDTBZANG")}

-- SELECT DISTINCT DRERZ, PVA FROM ${ref("JDTBZANG")}

-- SELECT DISTINCT CONCAT(DRERZ, '_', PVA) AS DRERZ_PVA
-- FROM `fmg-dcx-funke-connect.fmg_sap.JDTBZANG`


SELECT CONCAT(DRERZ, '_', PVA) AS DRERZ_PVA, COUNT(*) AS count_Fremde_Titel
FROM ${ref("JKAP")}
GROUP BY DRERZ_PVA


/*

SELECT table_name
FROM `fmg-dcx-funke-connect.fmg_sap.INFORMATION_SCHEMA.COLUMNS`
WHERE column_name IN ('PVA', 'DRERZ')
GROUP BY table_name
HAVING COUNT(DISTINCT column_name) = 2

SELECT table_name, column_name, data_type
FROM `fmg-dcx-funke-connect.fmg_sap.INFORMATION_SCHEMA.COLUMNS`
WHERE column_name IN ('PVA', 'DRERZ')
ORDER BY column_name,table_name


*/




